# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "./outputs"
description = "Llama 3 3B training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 100
enable_tensorboard = false
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "3B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "/proj/data-eng/tokenizers-llama3/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 4
seq_len = 4096
warmup_steps = 1000  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
# (bs, seq_len, steps) = (3, 8192, 152587) -> 30B tokens
#  steps = 152587
#100,000,000,000/4096/2/128=95367  128 GPUs bs=2 
#1,000,000,000,000/4096/4/128=476837  128 GPUs bs=4 
steps = 500000
data_parallel_degree = -1
tensor_parallel_degree = 1
compile = false
dataset = ""

[dataset]
use_experimental_dataloader = true
data_logical_shards = 1280 #768
bos_token = 128000
eos_token = 128001
dataset_path = "/proj/data-eng/blog/FineWeb-edu/parquets"
datasets = "lang=en"
dataset_weights = "1"
num_data_workers = 1
col_name = "tokens"
file_type = "arrow"

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 10000
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
